more updates

diff --git a/.github/workflows/cicd-workflow.yaml b/.github/workflows/cicd-workflow.yaml
--- a/.github/workflows/cicd-workflow.yaml
+++ b/.github/workflows/cicd-workflow.yaml
@@ -33,6 +33,44 @@ jobs:
       - name: Assign Diagrid Project
         run: |
           diagrid project use group-chat-microservice --api-key ${{secrets.DIAGRID_API_KEY}}
+      #Retrieve apiTokens for all project services
+      - name: Retrieve apiToken for each service
+        run: |
+          for service in ./services/*/ ; do
+            service_name=$(basename "$service")
+            # Fetch the Diagrid app identity information in JSON format
+            # Error handling if diagrid appid get command fails
+            if ! diagrid_output=$(diagrid appid get $service_name -o json 2>/dev/null); then
+              echo "Error: Failed to retrieve Diagrid app identity for $service_name"
+              continue  # Skip this service and move to the next one
+            fi
+            # Extract the apiToken using jq from the Diagrid output
+            api_token=$(echo $diagrid_output | jq -r '.status.apiToken')
+          
+            # Check if apiToken is null or empty
+            if [ -z "$api_token" ] || [ "$api_token" == "null" ]; then
+              echo "Error: No valid apiToken found for $service_name"
+              continue  # Skip this service and move to the next one
+            fi
+            
+            echo "API Token for $service_name: $api_token"
+          
+            # Create a JSON object with the service and apiToken
+            json_object=$(jq -n --arg service "$service_name" --arg apiToken "$api_token" \
+                          '{Service: $service, apiToken: $apiToken}')
+          
+            # Add the JSON object to the array
+            json_array=$(echo $json_array | jq --argjson obj "$json_object" '. += [$obj]')
+          done
+          # Save the JSON array to a file
+          echo $json_array | jq . > service_tokens.json
+        
+          # Output the JSON array
+          echo "Final JSON Array:"
+          cat service_tokens.json
+
+
+
       - name: Install other dependencies
         run: |
           npm install
@@ -102,8 +140,8 @@ jobs:
             echo "::set-output name=alb_dns::$alb_dns"
           
             # Create a JSON object with the service and ALB DNS
-            json_object=$(jq -n --arg service_name "$service_name" --arg alb_dns "$alb_dns" \
-                          '{Service: $service_name, Alb: $alb_dns}')
+            json_object=$(jq -n --arg service "$service_name" --arg alb_dns "$alb_dns" \
+                          '{Service: $service, Alb: $alb_dns}')
             
             # Add the JSON object to the array
             json_array=$(echo $json_array | jq --argjson obj "$json_object" '. += [$obj]')
